

# specify the PVT parameters
pvt: 
  corners:      ['tt', 'sf', 'ff', 'ss', 'fs', 'll', 'hh', 'hl', 'lh']
  # corners:      ['ll', 'hh', 'hl', 'lh']
  temperatures: [-40, 27, 125]
  # vdd:          [1.62, 1.8, 1.98]
  vdd:          [1.8]